#!/bin/bash

cat <<EOF
<HTML><CENTER>
COS/MAC ELF Computer Simulator<BR>
Build: $(date)<BR>
<BR>
<IMG SRC="COSMAC_ELF.png">
<BR>
Developed by Douglas Miller<BR>
https://github.com/durgadas311/cosmac-elf<BR>
<BR>
</CENTER></HTML>
EOF
